* emacs-fuzzy-module
An emacs module for doing fuzzy filtering of a list. 

I created this because I was encountering performance problems with ELisp-based solutions like flx-ido. I figure native module performance should be much better.

* Installation
1. To build, make sure you have Jam installed: 
: sudo apt install jam
2. Open Jamrules and add the path to your ~emacs/src~ to the ~HDRS~ variable. Ensure there is a space between the ~;~ and your path
3. Run ~jam~ in emacs-fuzzy-module directory
4. Open macoyFuzzy.el and make the ~module-load~ path reference ~macoyFuzzy.so~ (wherever you built it)
5. Evaluate macoyFuzzy.el
6. Add the following to your .emacs:
#+BEGIN_SRC emacs-lisp
(require 'macoy-fuzzy-ido)
(ido-mode 1)
(ido-everywhere 1)
(macoy-fuzzy-ido-mode 1)
#+END_SRC
* Building on Windows
~env JAM_TOOLSET=MINGW ../../nonRepos/jam-2.6/jam.exe -j4 -q~
gcc -c fuzzy.c -ggdb3 -Wall -fPIC -O0  -I. -I. -I../emacs/emacs/src
gcc -c utils.c -ggdb3 -Wall -fPIC -O0  -I. -I. -I../emacs/emacs/src
gcc -c macoyFuzzy.c -ggdb3 -Wall -fPIC -O0  -I. -I. -I../emacs/emacs/src
gcc -shared -o macoyFuzzy.dll fuzzy.o utils.o macoyFuzzy.o
